// Run with NODE_PATH pointing to the bundled node_modules and the local fixture running.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.INDUSTRY_TEST_BROWSER || 'msedge'});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.setDefaultTimeout(90000);
  await page.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:8773/')?route.continue():route.abort());
  await page.goto('http://127.0.0.1:8773/sales/industry-factory');
  await page.locator('#audience').selectOption('browser-audience');
  assert.equal(await page.locator('[name=market]').inputValue(),'Columbus, OH');
  await page.locator('[name=market]').fill('Columbus, OH');
  await page.locator('#save').click();
  await page.locator('#status').filter({hasText:'draft'}).waitFor();
  await page.locator('[data-action=generate-page]').click();
  await page.locator('#states').filter({hasText:'Landing page: ready'}).waitFor();
  await page.locator('[data-action=generate-report]').click();
  await page.locator('#states').filter({hasText:'Planning report: ready'}).waitFor();
  await page.locator('[data-step=review]').click();
  await page.locator('#technical-qa').filter({hasText:'PASS'}).waitFor();
  assert.ok(await page.frameLocator('#widget-preview').locator('#lead-form [name=company]').count());
  await page.frameLocator('#preview').getByRole('button',{name:'Find my weather opportunities'}).click();
  assert.equal(await page.frameLocator('#preview').locator('#lead-form button').isDisabled(),true);
  await page.screenshot({path:'../industry-factory-desktop.png',fullPage:true});
  await page.setViewportSize({width:375,height:900});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Factory has horizontal overflow');
  await page.screenshot({path:'../industry-factory-mobile.png',fullPage:true});
  for(const box of await page.locator('#qa input').all())await box.check();
  await page.locator('[data-step=publish]').click();
  await page.getByRole('button',{name:'Publish reviewed version'}).click();
  const link=page.getByRole('link',{name:'Open live campaign'});await link.waitFor();
  const publicPath=await link.getAttribute('href');
  await page.locator('#revise').click();
  await page.locator('#status').filter({hasText:'Version 2'}).waitFor();
  await page.locator('[name=market]').fill('Cleveland, OH');
  await page.locator('#copy-editor summary').click();
  await page.locator('[name=copy_headline]').fill('Roofing campaigns for Cleveland');
  await page.locator('#save').click();
  await page.locator('[data-action=generate-page]').click();
  await page.locator('[data-action=generate-report]').click();
  await page.locator('[data-step=review]').click();
  await page.locator('#comparison').filter({hasText:'Cleveland'}).waitFor();
  for(const box of await page.locator('#qa input').all())await box.check();
  await page.locator('[data-step=publish]').click();
  await page.locator('#publish').click();
  await page.locator('#status').filter({hasText:'published'}).waitFor();
  assert.equal(await page.getByRole('link',{name:'Open live campaign'}).getAttribute('href'),publicPath);
  await page.getByRole('button',{name:'Restore this version',exact:true}).click();
  await page.locator('#confirm-yes').click();
  await page.locator('#status').filter({hasText:'Version 1'}).waitFor();
  await page.locator('#unpublish').click();
  await page.locator('#confirm-yes').click();
  await page.locator('#status').filter({hasText:'archived'}).waitFor();
  assert.equal((await page.request.get('http://127.0.0.1:8773'+publicPath)).status(),404);
  await page.locator('.history-row').filter({hasText:'Version 1'}).getByRole('button',{name:'Restore this version'}).click();
  await page.locator('#confirm-yes').click();
  await page.locator('#status').filter({hasText:'published'}).waitFor();
  await page.goto('http://127.0.0.1:8773'+publicPath+'?utm_source=browser-test');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Published page has horizontal overflow');
  await page.getByRole('button',{name:'Find my weather opportunities'}).click();
  await page.locator('[name=company]').fill('Roof Test');await page.locator('[name=name]').fill('Test User');await page.locator('[name=email]').fill('test@example.test');
  let captured;
  await page.route('**/api/leads/capture',async route=>{captured=route.request().postDataJSON();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Temporary failure'})});});
  await page.locator('#lead-form button').click();
  await page.getByText('Temporary failure',{exact:true}).waitFor();
  assert.equal(await page.locator('#lead-form button').isEnabled(),true);
  assert.equal(captured.source,'landing');assert.equal(captured.meta.utm_source,'browser-test');
  await page.unroute('**/api/leads/capture');
  await page.locator('#lead-form button').click();await page.getByRole('link',{name:'Open my report'}).waitFor();
  const pageId=publicPath.split('/').pop();
  await page.goto('http://127.0.0.1:8773/test-parent/'+pageId+'?utm_source=embed-test');
  const widget=page.frameLocator('iframe');
  await widget.getByRole('button',{name:'Find my weather opportunities'}).click();
  await widget.locator('[name=company]').fill('Embed Roofing');
  await widget.locator('[name=name]').fill('Embed Tester');
  await widget.locator('[name=email]').fill('embed@example.test');
  await page.route('**/api/leads/capture',async route=>{captured=route.request().postDataJSON();await route.continue();});
  await widget.locator('#lead-form button').click();
  await widget.getByRole('link',{name:'Open my report'}).waitFor();
  assert.equal(captured.meta.utm_source,'embed-test');
  assert.equal(captured.meta.referrer,'http://127.0.0.1:8773/test-parent/'+pageId);
  assert.ok(await page.locator('iframe').evaluate(el=>parseInt(el.style.height)>920),'Embed did not resize after opening the form');
  console.log('PASS: saved audience, desktop/mobile factory, generation, preview guard, QA publish, revision comparison, stable address, restore, unpublish, lead retry and embed UTM capture.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
