"""The executive summary on a client's dashboard: generated by staff, read by
staff, saved by staff, and rendered -- never generated -- for the client.

    python3 test_reports_exec_summary.py

No pytest. A throwaway reports database (the SQLite file by default, the
job's Postgres when REPORTS_TEST_DATABASE_URL is set) and the composed app,
because the client's page lives under a mounted prefix and the staff page it
is edited from lives under the same one.

What it holds, and the first two are the whole point:

  * the client's public page NEVER reaches an AI call -- not on the page, not
    on data.json, not on the PDF -- and a stranger cannot reach either staff
    route;
  * nothing is published that a person did not read: drafting writes nothing
    at all, and only the save route puts words on the client's page;
  * the saved row carries who saved it and when, and a save with no name
    against it is refused;
  * saving bumps the link's updated_at, which is in the client page's cache
    key, so the words reach both workers rather than one of them in fifteen
    minutes;
  * a month that is not a month is refused rather than guessed at, and a
    90-day view is about no single month so it shows none;
  * no summary means no section at all, rather than a sentence about why;
  * taking one down returns the page to exactly that state.
"""
import os
import shutil
import sys
import tempfile
from datetime import date, timedelta
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT))

TMP = tempfile.mkdtemp(prefix="s1reports_execsum_")
os.environ["HUB_DATA_DIR"] = os.path.join(TMP, "data")
os.environ["AUDIT_LOG_PATH"] = os.path.join(TMP, "audit.jsonl")
os.environ["DATABASE_URL"] = "sqlite:///" + os.path.join(TMP, "hub.sqlite3")
import _reports_testdb                                              # noqa: E402
REPORTS_DB = _reports_testdb.bind(TMP)
os.environ["REPORTS_PROVIDER_SCHEMA"] = ""
os.environ["SECRET_KEY"] = "reports-exec-summary-test"
os.environ["PUBLIC_BASE_URL"] = "https://hub.example.test"
os.environ.pop("PANEL_PASSWORD", None)

_passed = _failed = 0


def check(label, got, want=True, note=None):
    global _passed, _failed
    if got == want:
        _passed += 1
        print(f"  ok    {label}")
    else:
        _failed += 1
        print(f"  FAIL  {label}\n          got:  {got!r}\n          want: {want!r}"
              + (f"\n          note: {note!r}" if note is not None else ""))


def section(title):
    print(f"\n{title}\n{'-' * len(title)}")


from werkzeug.test import Client                                    # noqa: E402

import wsgi                                                         # noqa: E402
from hub import auth                                                # noqa: E402
from modules.reports import app as reports_app                      # noqa: E402
from modules.reports import client_view, store                      # noqa: E402

_reports_testdb.reset(store)

TODAY = date.today()
MONTH = f"{TODAY:%Y-%m}"
LAST_MONTH = f"{(TODAY.replace(day=1) - timedelta(days=1)):%Y-%m}"
CLIENT = "d:buckeyelakewinery.com"
NAME = "Buckeye Lake Winery"

store.map_campaign("google", "a1", "c1", client=CLIENT, client_name=NAME,
                   product="Paid Search", mapped_by="tester")
store.confirm_mapping("google", "a1", "c1", by="tester")
store.upsert_rows([{"platform": "google", "account_id": "a1", "campaign_id": "c1",
                    "campaign_name": "Brand", "date": TODAY.replace(day=1),
                    "spend": 120.0, "impressions": 9000, "clicks": 300,
                    "conversions": 12, "source": "native"}], screen=False)
link = store.create_link(CLIENT, client_name=NAME, created_by="tester")
TOKEN = link.token

anon = Client(wsgi.application)
staff = Client(wsgi.application)
staff.set_cookie(auth.COOKIE_NAME, auth.issue_cookie_value("Todd"), domain="localhost")

DRAFT = ("Buckeye Lake Winery paid search delivered 12 conversions this month "
         "on $120.00 of media. Next month the plan is to widen the brand campaign.")
EDITED = DRAFT + " Reviewed and edited by a person before publishing."
LAST = "This is last month summary text."


def fake_ask(question, **kw):
    fake_ask.calls.append({"question": question, "kw": kw})
    return {"answer": DRAFT, "sources": [{"tool": "get_client_performance",
                                          "status": "ok"}],
            "recipe": kw.get("recipe", ""), "read_only": True}


fake_ask.calls = []


def draft(client=CLIENT, month=MONTH, who=staff):
    fake_ask.calls = []
    from hub import ask_smarthub
    with patch.object(ask_smarthub, "ask", side_effect=fake_ask):
        return who.post(f"/reports/client/{client}/summary/draft",
                        json={"month": month})


def save(text=EDITED, month=MONTH, action="save", who=staff):
    return who.post(f"/reports/client/{CLIENT}/summary",
                    data={"month": month, "text": text, "action": action})


def public(path=""):
    r = anon.get(f"/reports/r/c/{TOKEN}{path}")
    return r.status_code, r.get_data(as_text=True)


section("A stranger reaches neither staff route")
for path in (f"/reports/client/{CLIENT}/summary",
             f"/reports/client/{CLIENT}/summary/draft"):
    r = anon.post(path, data={"month": MONTH, "text": "published by nobody"})
    check(f"anonymous is refused on {path.rsplit('/', 1)[-1]}",
          r.status_code in (301, 302, 401, 403), True,
          f"answered {r.status_code}")
code, body = public()
check("...and nothing they could not reach was published",
      "published by nobody" not in body)

section("A demo session cannot spend AI credits on a draft")
# /api/ask-smarthub blocks demo sessions; this route reaches ask() directly,
# so it has to carry the same gate. A second door into a paid call is how a
# gate gets bypassed while every screen reports success.
os.environ["HUB_DEMO_MODE"] = "1"
try:
    r = draft()
    check("the draft route refuses a demo session", r.status_code, 403)
    check("...saying why, in the demo's own words",
          "demo session" in (r.get_json() or {}).get("error", ""))
    check("...and Ask SmartHub was never asked", len(fake_ask.calls), 0)
finally:
    os.environ.pop("HUB_DEMO_MODE", None)
r = draft()
check("...while a real session is not refused", r.status_code, 200)

section("Drafting writes nothing at all")
r = draft()
check("the draft route answers", r.status_code, 200)
payload = r.get_json()
check("...with the words", payload["text"], DRAFT)
check("...marked as a draft",
      "Nothing is published until you do." in payload["note"])
check("...naming what it read", payload["sources"][0]["tool"], "get_client_performance")
check("Ask SmartHub was asked once", len(fake_ask.calls), 1)
check("...through the monthly_exec recipe, so its framing rules apply",
      fake_ask.calls[0]["kw"]["recipe"], "monthly_exec")
check("...about this client", NAME in fake_ask.calls[0]["question"])
check("nothing was saved", store.exec_summary_for(store.get_link(TOKEN), MONTH), None)
code, body = public()
check("...and the client's page shows no summary section",
      "Summary" not in body and DRAFT not in body)

section("The month is validated, never guessed at")
check("a month that is not a month is refused",
      draft(month="2026-13").status_code, 400)
check("...and so is an empty one", draft(month="").status_code, 400)
check("...and words", draft(month="September").status_code, 400)
check("no AI call was made for any of them", len(fake_ask.calls), 0)

section("Saving is what publishes, and it carries a name")
before = store.get_link(TOKEN).updated_at
r = save()
check("the save redirects back to the staff page", r.status_code, 302)
entry = store.exec_summary_for(store.get_link(TOKEN), MONTH)
check("the words are saved", entry["text"], EDITED)
check("...the EDITED words, not the draft", entry["text"] != DRAFT, True)
check("...under the month they are about", entry["month"], MONTH)
check("...with who saved them", entry["generated_by"], "Todd")
check("...and when", bool(entry["generated_at"]))
check("the link's updated_at moved, so the page cache key changes",
      store.get_link(TOKEN).updated_at != before)

section("The client's page renders the saved words, and asks for none")
fake_ask.calls = []
code, body = public()
check("the public page renders", code, 200)
check("...with the summary", EDITED in body)
check("...under a heading", "Summary" in body)
check("no AI call was made serving it", len(fake_ask.calls), 0)
code, data = public("/data.json")
check("data.json carries it too", code, 200)
check("...as saved text", EDITED in data)
check("...and still no AI call", len(fake_ask.calls), 0)
r = anon.get(f"/reports/r/c/{TOKEN}.pdf")
check("the PDF renders", r.status_code, 200)
check("...with no AI call either", len(fake_ask.calls), 0)

section("Refusals in the store itself")


def _raises(fn, *a, **kw) -> str:
    try:
        fn(*a, **kw)
    except ValueError as exc:
        return str(exc)
    return ""


check("a summary with no text is refused",
      "needs some text" in _raises(store.save_exec_summary, TOKEN,
                                   month=MONTH, text="   ", by="Todd"))
check("a summary with nobody behind it is refused",
      "needs a name" in _raises(store.save_exec_summary, TOKEN,
                                month=MONTH, text="words", by=""))
check("a summary with no month is refused",
      "needs the month" in _raises(store.save_exec_summary, TOKEN,
                                   month="", text="words", by="Todd"))
check("a summary on a link that does not exist is refused",
      "No such report link" in _raises(store.save_exec_summary, "nope",
                                       month=MONTH, text="words", by="Todd"))
check("a very long summary is cut, not refused",
      len(store.save_exec_summary(TOKEN, month="2020-01", text="x" * 9000,
                                  by="Todd")["text"]),
      store.EXEC_SUMMARY_MAX)
store.clear_exec_summary(TOKEN, "2020-01")

section("One month's summary does not become another's")
save(text=LAST, month=LAST_MONTH)
check("last month is saved separately",
      store.exec_summary_for(store.get_link(TOKEN), LAST_MONTH)["text"],
      LAST)
check("...and this month is untouched",
      store.exec_summary_for(store.get_link(TOKEN), MONTH)["text"], EDITED)
code, body = public()
check("the month-to-date page shows this month's",
      EDITED in body and LAST not in body)
code, body = public("?period=90d")
check("the 90-day view is about no single month, so it shows none",
      LAST not in body and EDITED not in body)
check("...and the page still renders", code, 200)

section("A summary is client copy, so it carries client punctuation safely")
from markupsafe import escape as _escape                            # noqa: E402
APOSTROPHE = ("Buckeye Lake Winery's \"best month yet\": conversions rose & "
              "cost per conversion fell <20%.")
save(text=APOSTROPHE, month=MONTH)
check("it is stored exactly as typed",
      store.exec_summary_for(store.get_link(TOKEN), MONTH)["text"], APOSTROPHE)
code, body = public()
# Jinja's own escaping, not Python's html.escape: the two spell a double
# quote differently (&#34; against &quot;) and asserting the wrong one passes
# or fails for a reason that has nothing to do with the page.
check("...rendered escaped, so no markup reaches the page",
      str(_escape(APOSTROPHE)) in body)
check("...and the raw angle bracket is not loose in the HTML",
      "fell <20%" not in body)
check("...while data.json carries the real characters",
      APOSTROPHE in public("/data.json")[1].replace("\\u0026", "&")
      or "Winery's" in public("/data.json")[1])
save(text=EDITED, month=MONTH)

section("Taking it down returns the page to showing none")
r = save(action="remove", month=MONTH)
check("the take-down redirects back", r.status_code, 302)
check("...the row is gone", store.exec_summary_for(store.get_link(TOKEN), MONTH), None)
code, body = public()
check("...the client's page shows no summary section", EDITED not in body)
check("...and no sentence about why it is missing",
      "no summary" not in body.lower())

section("The staff page carries the form, and says what is published")
r = staff.get(f"/reports/client/{CLIENT}")
body = r.get_data(as_text=True)
check("the staff page renders", r.status_code, 200)
check("...with the summary form", 'id="summaryForm"' in body)
check("...a draft button that writes nothing", 'id="summaryDraft"' in body)
check("...and a save button that does", 'value="save"' in body)
check("...saying nothing is published yet",
      "Nothing is published for this month" in body)
save()
body = staff.get(f"/reports/client/{CLIENT}").get_data(as_text=True)
check("...and once published, who published it", "Todd" in body)
check("...with the saved words in the box for editing", EDITED in body)

section("Every press is on the activity log")
from hub import audit                                               # noqa: E402
rows = audit.read(limit=500, module="reports")
kinds = {r.get("type") for r in rows}
check("the draft is logged", "reports_summary_drafted" in kinds)
check("the save is logged", "reports_summary_saved" in kinds)
check("the take-down is logged", "reports_summary_removed" in kinds)
check("...against the client", NAME in {r.get("client") for r in rows})

section("Nothing in the client-facing path can generate one")
public_src = (ROOT / "modules" / "reports" /
              "templates" / "reports_client_public.html").read_text(encoding="utf-8")
check("the client's template never calls a draft route",
      "summary/draft" not in public_src)
check("...and never names Ask SmartHub", "ask-smarthub" not in public_src.lower())
pdf_src = (ROOT / "modules" / "reports" / "client_pdf.py").read_text(encoding="utf-8")
check("the PDF builder never calls one", "summary/draft" not in pdf_src)
view_src = (ROOT / "modules" / "reports" / "client_view.py").read_text(encoding="utf-8")
check("the client view reads the saved row and asks for nothing",
      "exec_summary_for" in view_src and "ask_smarthub" not in view_src)

shutil.rmtree(TMP, ignore_errors=True)
print(f"\n{_passed} passed, {_failed} failed")
sys.exit(1 if _failed else 0)
