// Run with NODE_PATH pointing to the bundled node_modules and the local fixture running.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.INDUSTRY_TEST_BROWSER || 'msedge'});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.setDefaultTimeout(90000);
  await page.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:8773/')?route.continue():route.abort());
  await page.goto('http://127.0.0.1:8773/sales/industry-factory');
  await page.locator('[name=market]').fill('Columbus, OH');
  await page.getByRole('button',{name:'Create draft',exact:true}).click();
  await page.locator('#status').filter({hasText:'draft'}).waitFor();
  await page.getByRole('button',{name:'Generate page',exact:true}).click();
  await page.locator('#states').filter({hasText:'Page: ready'}).waitFor();
  await page.getByRole('button',{name:'Generate report',exact:true}).click();
  await page.locator('#states').filter({hasText:'Report: ready'}).waitFor();
  await page.frameLocator('#preview').getByRole('button',{name:'Find my weather opportunities'}).click();
  assert.equal(await page.frameLocator('#preview').locator('#lead-form button').isDisabled(),true);
  await page.screenshot({path:'../industry-factory-desktop.png',fullPage:true});
  await page.setViewportSize({width:375,height:900});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Factory has horizontal overflow');
  await page.screenshot({path:'../industry-factory-mobile.png',fullPage:true});
  for(const box of await page.locator('#qa input').all())await box.check();
  await page.getByRole('button',{name:'Publish reviewed version'}).click();
  const link=page.getByRole('link',{name:'Open published page'});await link.waitFor();
  const publicPath=await link.getAttribute('href');
  await page.goto('http://127.0.0.1:8773'+publicPath+'?utm_source=browser-test');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Published page has horizontal overflow');
  await page.getByRole('button',{name:'Find my weather opportunities'}).click();
  await page.locator('[name=company]').fill('Roof Test');await page.locator('[name=name]').fill('Test User');await page.locator('[name=email]').fill('test@example.test');
  let captured;
  await page.route('**/api/leads/capture',async route=>{captured=route.request().postDataJSON();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Temporary failure'})});});
  await page.locator('#lead-form button').click();
  await page.getByText('Temporary failure',{exact:true}).waitFor();
  assert.equal(await page.locator('#lead-form button').isEnabled(),true);
  assert.equal(captured.source,'landing');assert.equal(captured.meta.utm_source,'browser-test');
  await page.unroute('**/api/leads/capture');
  await page.locator('#lead-form button').click();await page.getByRole('link',{name:'Open my report'}).waitFor();
  const pageId=publicPath.split('/').pop();
  await page.goto('http://127.0.0.1:8773/test-parent/'+pageId+'?utm_source=embed-test');
  const widget=page.frameLocator('iframe');
  await widget.getByRole('button',{name:'Find my weather opportunities'}).click();
  await widget.locator('[name=company]').fill('Embed Roofing');
  await widget.locator('[name=name]').fill('Embed Tester');
  await widget.locator('[name=email]').fill('embed@example.test');
  await page.route('**/api/leads/capture',async route=>{captured=route.request().postDataJSON();await route.continue();});
  await widget.locator('#lead-form button').click();
  await widget.getByRole('link',{name:'Open my report'}).waitFor();
  assert.equal(captured.meta.utm_source,'embed-test');
  assert.equal(captured.meta.referrer,'http://127.0.0.1:8773/test-parent/'+pageId);
  assert.ok(await page.locator('iframe').evaluate(el=>parseInt(el.style.height)>920),'Embed did not resize after opening the form');
  console.log('PASS: desktop/mobile factory, draft generation, preview guard, QA publish, responsive public page, failed lead retry and UTM capture.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
