/**
 * Source-image ceiling.
 *
 * Every image that becomes part of an ad — whether uploaded by the customer,
 * pulled from Pixabay, or generated by AI — must end up a valid raster under
 * 150 KB. This is the ONE place that guarantees it, so no ingest path can
 * forget the rule.
 *
 * The guarantee is not "reject if too big" but "make it fit": a 4 MB phone
 * photo is downscaled and re-encoded until it is under budget, because
 * rejecting a customer's only photo helps no one. Only genuinely unusable
 * input (not an image, zero bytes) is refused.
 *
 * 150 KB is the source budget the brief specified. It is the same number as
 * Google's delivered-creative ceiling rather than below it -- this file used
 * to say "deliberately below", which is not a thing 150 can be than 150. What
 * actually keeps a finished ad inside its platform limit is the quality ladder
 * `render.ts` steps on the composed raster; this budget keeps a 6 MB phone
 * photo from being the input to that, which is a different job and worth
 * having, just not the one the sentence claimed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import sharp from 'sharp';

export const MAX_IMAGE_BYTES = 150 * 1024;

/** Bytes as a person reads them. `toFixed(0)` printed a 600-byte logo as
 *  "0 KB", which is not a size anybody can act on. */
function kb(bytes: number): string {
  return bytes < 10 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${Math.round(bytes / 1024)} KB`;
}

export interface FitResult {
  /** Path to the written, under-budget image. */
  file: string;
  bytes: number;
  width: number;
  height: number;
  format: string;
  /**
   * True if the image genuinely had to be reduced: it arrived over budget, or
   * over the dimension cap, or the first encode was still too big.
   *
   * It used to be `encoded.length !== original.length`, which is true of very
   * nearly every image -- the file is always re-encoded, so the bytes always
   * differ. So a 600-byte logo came back `reencoded: true` with a note saying
   * it had been "optimized ... to meet the 150 KB limit", about a file that
   * was 0.4% of that limit and had needed nothing. The field's own description
   * said "had to", and the value meant "we did".
   */
  reencoded: boolean;
  /** Human note when something was done to the file, for surfacing in the UI. */
  note?: string;
}

/**
 * Take an image (buffer or path), guarantee it is a valid raster under
 * MAX_IMAGE_BYTES, and write it to `outFile`. Throws only if the input is not
 * a usable image at all.
 *
 * `keepAlpha` preserves transparency (for logos); heroes and backgrounds are
 * flattened to JPEG, which compresses photographs far smaller than PNG.
 */
export async function fitImageToBudget(
  input: Buffer | string,
  outFile: string,
  opts: { keepAlpha?: boolean; maxDimension?: number } = {},
): Promise<FitResult> {
  let img = sharp(input, { failOn: 'error' });
  let meta;
  try {
    meta = await img.metadata();
  } catch {
    throw new Error('That file is not a readable image.');
  }
  if (!meta.width || !meta.height) throw new Error('That image has no dimensions — it may be corrupt.');

  fs.mkdirSync(path.dirname(outFile), { recursive: true });

  const keepAlpha = opts.keepAlpha ?? (meta.hasAlpha && meta.format === 'png');
  const maxDim = opts.maxDimension ?? 2000; // no source needs to exceed this for display ads

  const originalBytes = typeof input === 'string' ? fs.statSync(input).size : input.length;

  // First pass: cap dimensions (a 6000px photo is pure waste for a 970px ad).
  let width = meta.width;
  let height = meta.height;
  const capped = Math.max(meta.width, meta.height) > maxDim;
  if (capped) {
    const s = maxDim / Math.max(width, height);
    width = Math.round(width * s);
    height = Math.round(height * s);
  }

  async function encode(w: number, h: number, quality: number): Promise<Buffer> {
    const pipe = sharp(input).resize({ width: w, height: h, fit: 'inside', withoutEnlargement: true });
    return keepAlpha
      ? pipe.png({ compressionLevel: 9, quality }).toBuffer()
      : pipe.flatten({ background: '#ffffff' }).jpeg({ quality, mozjpeg: true }).toBuffer();
  }

  // Try progressively harder: drop quality, then dimensions, until under budget.
  let buf = await encode(width, height, 82);
  const squeezed = buf.length > MAX_IMAGE_BYTES;
  let quality = 82;
  let guard = 0;
  while (buf.length > MAX_IMAGE_BYTES && guard++ < 12) {
    if (quality > 40) {
      quality -= 12;
    } else {
      // Quality is as low as we'll go; shrink dimensions 15% and reset quality.
      width = Math.round(width * 0.85);
      height = Math.round(height * 0.85);
      quality = 70;
    }
    buf = await encode(width, height, quality);
  }

  if (buf.length > MAX_IMAGE_BYTES) {
    throw new Error('Could not compress this image under 150 KB — please use a simpler or smaller image.');
  }

  // This function exists to make a file smaller, and on a high-entropy source
  // already saved hard -- a Pixabay `webformatURL`, a low-quality photo -- a
  // q82 re-encode comes back *larger*. It was written out anyway, and the note
  // then read "Optimized from 52 KB to 137 KB". Where the input already fits
  // the budget, is inside the dimension cap and is already the format we would
  // write, the original bytes are the better answer and are kept.
  // Note this asks nothing about whether the ladder had to run. It routinely
  // does -- the q82 first pass on such a source overshoots the budget, the
  // loop pulls it back under, and the answer is still larger than what we were
  // handed. Work having been done is not a reason to prefer a worse result.
  const sameFormat = keepAlpha ? meta.format === 'png' : meta.format === 'jpeg';
  const keepOriginal =
    buf.length > originalBytes && !capped && sameFormat && originalBytes <= MAX_IMAGE_BYTES;
  if (keepOriginal) {
    buf = typeof input === 'string' ? fs.readFileSync(input) : input;
  }

  const finalMeta = await sharp(buf).metadata();
  fs.writeFileSync(outFile, buf);

  // Keeping the original means nothing was achieved, whatever the ladder did.
  const reencoded = !keepOriginal && (originalBytes > MAX_IMAGE_BYTES || capped || squeezed);
  return {
    file: outFile,
    bytes: buf.length,
    width: finalMeta.width ?? width,
    height: finalMeta.height ?? height,
    format: keepAlpha ? 'png' : 'jpg',
    reencoded,
    note: reencoded ? `Optimized from ${kb(originalBytes)} to ${kb(buf.length)} to meet the 150 KB limit.` : undefined,
  };
}
