/**
 * Making a logo legible by moving the palette, not the logo.
 *
 * A client's mark is the one asset in a campaign nobody may edit. When it is
 * a dark logo and the layout puts it on the dark brand colour, the choices
 * used to be: ship it invisible, swap to the reverse logo if one exists, or
 * hand-pick a new brand colour in five swatches and hope. QA said *that* the
 * logo was invisible and could do nothing about it.
 *
 * So this proposes whole palettes that make the existing mark read, and a
 * person picks one. Three things about how:
 *
 * **It is arithmetic, not a model.** "Ask AI for a colour that contrasts" is
 * a slow, per-call-billed, non-deterministic way to do a subtraction whose
 * right answer is defined by a published formula — and the answer has to be
 * checkable, because the whole point is that the result provably reads. Every
 * variant here is generated by walking a channel until the WCAG ratio clears
 * the target, and every one is returned with the ratio it achieves so the
 * screen can show its work.
 *
 * **The client's real colours come first.** Where the Hub has an Insites scan
 * of their website, the colours that site actually uses are a better source
 * than anything computed: they are the client's palette, observed, rather
 * than a tint of one entry in it. Those variants are offered first and
 * labelled as observed.
 *
 * **Nothing is applied.** These are proposals with a reason attached, in the
 * same shape as everything else in this module that a person accepts.
 */

import { contrastRatio, hexLuminance } from './raster';
import type { Brand } from './types';

/** WCAG's large-text threshold. A logo is a graphic, not body copy, and 3:1
 *  is the level at which a mark reads as a mark rather than a smudge. */
export const LOGO_TARGET = 3;

/** Below this the logo is not merely low-contrast, it is invisible. */
export const LOGO_INVISIBLE = 1.7;

export interface PaletteVariant {
  id: string;
  /** What to call it on a button. */
  name: string;
  /** Why this one, in a sentence a person can disagree with. */
  why: string;
  /** The full five roles. Applying a partial palette is how a set ends up
   *  half in one scheme and half in another. */
  colors: Brand['colors'];
  /** The contrast this achieves between the logo and the colour behind it. */
  ratio: number;
  /** 'observed' = read off the client's own website by an Insites scan;
   *  'computed' = derived here from the palette they already have. */
  source: 'observed' | 'computed';
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  const f = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
  return [
    parseInt(f.slice(0, 2), 16) || 0,
    parseInt(f.slice(2, 4), 16) || 0,
    parseInt(f.slice(4, 6), 16) || 0,
  ];
}

const rgbToHex = (r: number, g: number, b: number) =>
  '#' + [r, g, b]
    .map((n) => Math.round(Math.max(0, Math.min(255, n))).toString(16).padStart(2, '0'))
    .join('')
    .toUpperCase();

export function isHex(value: unknown): value is string {
  return typeof value === 'string' && /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(value.trim());
}

/**
 * The same hue, moved toward white or black until it clears `target` against
 * `inkLum`.
 *
 * Lightness rather than hue on purpose: a client's blue that has been made
 * paler is still recognisably their blue, and a different colour that happens
 * to contrast is not their brand at all. Returns null when even pure white or
 * pure black cannot clear the target, which happens with a mid-grey mark.
 */
export function shiftUntilReadable(
  color: string,
  inkLum: number,
  target = LOGO_TARGET,
  toward: 'lighter' | 'darker' = 'lighter',
): { hex: string; ratio: number } | null {
  const [r, g, b] = hexToRgb(color);
  let best: { hex: string; ratio: number } | null = null;
  for (let step = 1; step <= 24; step++) {
    const t = step / 24;
    const hex = toward === 'lighter'
      ? rgbToHex(r + (255 - r) * t, g + (255 - g) * t, b + (255 - b) * t)
      : rgbToHex(r * (1 - t), g * (1 - t), b * (1 - t));
    const ratio = contrastRatio(inkLum, hexLuminance(hex));
    if (ratio >= target) return { hex, ratio };
    if (!best || ratio > best.ratio) best = { hex, ratio };
  }
  // Nothing in this direction cleared it. The caller decides whether the best
  // effort is worth offering; it is not returned as a success.
  return null;
}

/**
 * Palettes that would make this logo read.
 *
 * `behind` is the brand role the logo actually sits on for the size being
 * looked at — usually `background`, but a layout that puts the logo on a
 * panel passes that panel's fill instead. Getting this from the caller rather
 * than guessing is what stops the tool proposing a fix for the wrong colour.
 */
export function paletteVariants(opts: {
  brand: Brand;
  /** Mean luminance of the logo's visible pixels, 0..1. */
  logoLuminance: number;
  /** Which brand role sits behind the logo. */
  behind: keyof Brand['colors'];
  /** The client's own website colours, where a scan has read them. */
  observed?: Partial<Record<'background' | 'text' | 'accent', string>>;
  target?: number;
}): { ratio: number; verdict: 'invisible' | 'weak' | 'fine'; variants: PaletteVariant[] } {
  const { brand, logoLuminance, behind } = opts;
  const target = opts.target ?? LOGO_TARGET;
  const current = brand.colors[behind];
  const ratio = contrastRatio(logoLuminance, hexLuminance(current));
  const verdict = ratio < LOGO_INVISIBLE ? 'invisible' : ratio < target ? 'weak' : 'fine';

  // Nothing to fix. Offering four ways to change a palette that already works
  // is how a tool teaches people to ignore it.
  if (verdict === 'fine') return { ratio, verdict, variants: [] };

  const variants: PaletteVariant[] = [];
  const push = (v: PaletteVariant) => {
    const hex = v.colors[behind];
    // A "change" to the colour it already is. The shift walk returns one of
    // these whenever the current colour is already at the end of its range —
    // "#FFFFFF keeps its hue and moves to #FFFFFF" is not a proposal.
    if (hex.toUpperCase() === current.toUpperCase()) return;
    // Two routes landing on the same hex are one choice wearing two labels.
    if (variants.some((x) => x.colors[behind].toUpperCase() === hex.toUpperCase())) return;
    // `light` and `dark` are the only two roles whose NAME asserts something
    // about the colour, and every template resolves ink against them on that
    // assumption. Setting `light` to near-black fixes the logo and inverts
    // the meaning of the role for every other block on every other size.
    if ((behind === 'light' || behind === 'dark')) {
      const isLight = hexLuminance(hex) > 0.5;
      if ((behind === 'light') !== isLight) return;
    }
    variants.push(v);
  };

  // 1. The client's own site, where a scan has seen it. Their real colours
  //    beat any tint we can compute, so these come first.
  for (const [role, label] of [
    ['background', 'their site background'],
    ['accent', 'their site accent'],
  ] as const) {
    const hex = opts.observed?.[role];
    if (!isHex(hex)) continue;
    const r = contrastRatio(logoLuminance, hexLuminance(hex));
    if (r < target) continue;
    push({
      id: `observed-${role}`,
      name: `Use ${label}`,
      why: `Their website uses ${hex} ${role === 'background' ? 'behind its content' : 'as its accent'}, ` +
        `and the logo reads at ${r.toFixed(1)}:1 on it. Read from their latest site scan.`,
      colors: { ...brand.colors, [behind]: hex },
      ratio: r,
      source: 'observed',
    });
  }

  // 2. Their own colour, moved. Same hue, so it still reads as their brand.
  for (const toward of ['lighter', 'darker'] as const) {
    const shifted = shiftUntilReadable(current, logoLuminance, target, toward);
    if (!shifted) continue;
    push({
      id: `shift-${toward}`,
      name: toward === 'lighter' ? 'A lighter version of their color'
                                 : 'A darker version of their color',
      why: `${current} keeps its hue and moves to ${shifted.hex}, which the logo reads on ` +
        `at ${shifted.ratio.toFixed(1)}:1. Still recognisably their color.`,
      colors: { ...brand.colors, [behind]: shifted.hex },
      ratio: shifted.ratio,
      source: 'computed',
    });
  }

  // 3. Another role they already have. No new colour invented at all — this
  //    is the best outcome when it works, and often it does.
  for (const role of ['secondary', 'accent', 'light', 'dark', 'primary'] as const) {
    if (role === behind) continue;
    const hex = brand.colors[role];
    if (!isHex(hex)) continue;
    const r = contrastRatio(logoLuminance, hexLuminance(hex));
    if (r < target) continue;
    push({
      id: `role-${role}`,
      name: `Use their ${role} color`,
      why: `${hex} is already in their palette and the logo reads on it at ${r.toFixed(1)}:1. ` +
        `Nothing new is invented.`,
      colors: { ...brand.colors, [behind]: hex },
      ratio: r,
      source: 'computed',
    });
  }

  // Strongest contrast first — that is the order somebody scanning this wants.
  variants.sort((a, b) => (a.source === b.source ? b.ratio - a.ratio
                                                 : a.source === 'observed' ? -1 : 1));
  return { ratio, verdict, variants };
}
